import { describe, expect, it } from 'vitest';
import {
  HOOK_TIMEOUT_SECONDS,
  NOTIFICATION_MATCHER,
  buildRunScript,
  buildSettings,
  buildSettingsFile,
  buildStatuslineScript,
  claudeArgv,
  claudeCommandLine,
  hookCommand,
  hookUrl,
  launcherUrl,
  shellQuote,
  type RunScriptContext,
} from '../../src/connectors/runners/claude-tmux/session-files.js';
import { HOOK_EVENT_NAMES } from '../../src/core/state-machine.js';

const SESSION_ID = 'qc-DOC-1-implement';
const DIR = '/data/questionable-choices/sessions/qc-DOC-1-implement';
const PORT = 4400;

const RUN_CONTEXT: RunScriptContext = {
  sessionId: SESSION_ID,
  port: PORT,
  dir: DIR,
  claudeBin: 'claude',
  issueKey: 'DOC-1',
  model: 'claude-fable-5-1',
  effort: 'high',
  permissionMode: 'acceptEdits',
  needsBootstrap: true,
  bootstrap: 'npm ci',
  resumeSessionId: null,
};

describe('shellQuote', () => {
  it('wraps a value in single quotes', () => {
    expect(shellQuote('/data/sessions/qc-DOC-1')).toBe("'/data/sessions/qc-DOC-1'");
  });

  it('escapes an embedded single quote', () => {
    expect(shellQuote("it's")).toBe("'it'\\''s'");
  });
});

describe('hookUrl and launcherUrl', () => {
  it('address the loopback ingress of one session', () => {
    expect(hookUrl(PORT, SESSION_ID, 'Stop')).toBe(
      'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/Stop',
    );
    expect(launcherUrl(PORT, SESSION_ID, 'claude-exit')).toBe(
      'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/launcher/claude-exit',
    );
  });
});

describe('hookCommand', () => {
  it('posts stdin and never fails the session', () => {
    expect(hookCommand(PORT, SESSION_ID, 'PreToolUse')).toBe(
      "curl -s -m 2 -X POST -H 'content-type: application/json' --data-binary @- http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/PreToolUse >/dev/null 2>&1 || true",
    );
  });
});

describe('buildSettings', () => {
  const settings = buildSettings({ sessionId: SESSION_ID, port: PORT, dir: DIR });

  it('subscribes to every hook the state machine consumes', () => {
    expect(Object.keys(settings.hooks)).toEqual([...HOOK_EVENT_NAMES]);
  });

  it('gives every hook a five-second timeout and its own ingress path', () => {
    for (const event of HOOK_EVENT_NAMES) {
      const entry = settings.hooks[event]![0]!;
      expect(entry.hooks).toHaveLength(1);
      expect(entry.hooks[0]!.type).toBe('command');
      expect(entry.hooks[0]!.timeout).toBe(HOOK_TIMEOUT_SECONDS);
      expect(entry.hooks[0]!.command).toContain(`/api/hooks/${SESSION_ID}/${event}`);
    }
  });

  it('matches only the two notification types that mean the owner is needed', () => {
    expect(settings.hooks['Notification']![0]!.matcher).toBe(NOTIFICATION_MATCHER);
    expect(settings.hooks['Stop']![0]!.matcher).toBeUndefined();
  });

  it('overrides the status line with the generated script, refreshed every second', () => {
    expect(settings.statusLine).toEqual({
      type: 'command',
      command: `bash ${DIR}/statusline.sh`,
      refreshInterval: 1,
    });
  });
});

describe('buildSettingsFile', () => {
  it('renders the exact JSON document', () => {
    const file = buildSettingsFile({ sessionId: SESSION_ID, port: PORT, dir: DIR });

    expect(file).toBe(
      `${JSON.stringify(buildSettings({ sessionId: SESSION_ID, port: PORT, dir: DIR }), null, 2)}\n`,
    );
    expect(file.endsWith('\n')).toBe(true);
  });
});

describe('buildStatuslineScript', () => {
  it('posts the payload in the background and prints nothing without a chain', () => {
    const script = buildStatuslineScript({
      sessionId: SESSION_ID,
      port: PORT,
      chainedCommand: null,
    });

    expect(script).toBe(
      [
        '#!/usr/bin/env bash',
        '# Generated by questionable-choices. Overwritten on every start.',
        '',
        'payload=$(cat)',
        "printf '%s' \"$payload\" | curl -s -m 1 -X POST -H 'content-type: application/json' --data-binary @- 'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/statusline' >/dev/null 2>&1 &",
        '',
      ].join('\n'),
    );
  });

  it('pipes the same payload into the owner statusline when there is one', () => {
    const script = buildStatuslineScript({
      sessionId: SESSION_ID,
      port: PORT,
      chainedCommand: 'bash ~/.claude/statusline.sh',
    });

    expect(script.endsWith('printf \'%s\' "$payload" | bash ~/.claude/statusline.sh\n')).toBe(true);
  });
});

describe('claudeArgv', () => {
  it('passes the settings file, the issue key, the model and the effort', () => {
    expect(claudeArgv(RUN_CONTEXT)).toEqual([
      '--settings',
      `${DIR}/settings.json`,
      '--name',
      'DOC-1',
      '--model',
      'claude-fable-5-1',
      '--effort',
      'high',
      '--permission-mode',
      'acceptEdits',
    ]);
  });

  it('passes no permission-mode flag for the default sentinel', () => {
    expect(claudeArgv({ ...RUN_CONTEXT, permissionMode: 'default' })).not.toContain(
      '--permission-mode',
    );
  });

  it('resumes by claude session id', () => {
    const argv = claudeArgv({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });
    expect(argv.slice(-2)).toEqual(['--resume', 'abc-123']);
  });
});

describe('claudeCommandLine', () => {
  it('reads the prompt out of prompt.txt on a fresh start', () => {
    expect(claudeCommandLine(RUN_CONTEXT)).toBe(
      `'claude' '--settings' '${DIR}/settings.json' '--name' 'DOC-1' '--model' 'claude-fable-5-1' '--effort' 'high' '--permission-mode' 'acceptEdits' "$(cat '${DIR}/prompt.txt')"`,
    );
  });

  it('sends no prompt on a resume', () => {
    const line = claudeCommandLine({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });
    expect(line).toContain("'--resume' 'abc-123'");
    expect(line).not.toContain('prompt.txt');
  });
});

describe('buildRunScript', () => {
  it('renders the whole launcher for a bootstrapped start', () => {
    expect(buildRunScript(RUN_CONTEXT)).toBe(
      [
        '#!/usr/bin/env bash',
        '# Generated by questionable-choices. Overwritten on every start.',
        'set -u',
        '',
        'post() {',
        `  curl -s -m 2 -X POST -H 'content-type: application/json' --data-binary "$2" "http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/launcher/$1" >/dev/null 2>&1 || true`,
        '}',
        '',
        "post bootstrap-start '{}'",
        '',
        'npm ci',
        'status=$?',
        'if [ "$status" -ne 0 ]; then',
        '  post bootstrap-failed "{\\"exitCode\\":$status}"',
        '  exec bash',
        'fi',
        '',
        "post claude-start '{}'",
        '',
        `'claude' '--settings' '${DIR}/settings.json' '--name' 'DOC-1' '--model' 'claude-fable-5-1' '--effort' 'high' '--permission-mode' 'acceptEdits' "$(cat '${DIR}/prompt.txt')"`,
        'status=$?',
        '',
        'post claude-exit "{\\"exitCode\\":$status}"',
        '',
        'exec bash',
        '',
      ].join('\n'),
    );
  });

  it('skips the bootstrap block when the checkout is reused', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, needsBootstrap: false });

    expect(script).toContain("post bootstrap-start '{}'");
    expect(script).not.toContain('npm ci');
    expect(script).not.toContain('bootstrap-failed');
  });

  it('skips the bootstrap block when the workspace configures none', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, bootstrap: null });

    expect(script).not.toContain('bootstrap-failed');
  });

  it('keeps the window open after claude exits', () => {
    expect(buildRunScript(RUN_CONTEXT).trimEnd().endsWith('exec bash')).toBe(true);
  });

  it('tells the launcher ingress that a resume launch is a resume', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });

    expect(script).toContain('post claude-start \'{"mode":"resume"}\'');
    expect(script).not.toContain("post claude-start '{}'");
  });
});
