import { spawn } from 'node:child_process';
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  BOOTSTRAP_LOG_FILE,
  BOOTSTRAP_TAIL_LINES,
  BYPASS_PERMISSIONS_FLAG,
  HOOK_TIMEOUT_SECONDS,
  NOTIFICATION_MATCHER,
  buildRunScript,
  buildSettings,
  buildSettingsFile,
  buildStatuslineScript,
  claudeArgv,
  claudeCommandLine,
  hookCommand,
  hookUrl,
  launcherUrl,
  shellQuote,
  type RunScriptContext,
} from '../../src/connectors/runners/claude-tmux/session-files.js';
import { HOOK_EVENT_NAMES } from '../../src/core/state-machine.js';

const SESSION_ID = 'qc-DOC-1-implement';
const DIR = '/data/questionable-choices/sessions/qc-DOC-1-implement';
const PORT = 4400;

const RUN_CONTEXT: RunScriptContext = {
  sessionId: SESSION_ID,
  port: PORT,
  dir: DIR,
  claudeBin: 'claude',
  issueKey: 'DOC-1',
  model: 'claude-fable-5-1',
  effort: 'high',
  permissionMode: 'acceptEdits',
  needsBootstrap: true,
  bootstrap: 'npm ci',
  resumeSessionId: null,
};

describe('shellQuote', () => {
  it('wraps a value in single quotes', () => {
    expect(shellQuote('/data/sessions/qc-DOC-1')).toBe("'/data/sessions/qc-DOC-1'");
  });

  it('escapes an embedded single quote', () => {
    expect(shellQuote("it's")).toBe("'it'\\''s'");
  });
});

describe('hookUrl and launcherUrl', () => {
  it('address the loopback ingress of one session', () => {
    expect(hookUrl(PORT, SESSION_ID, 'Stop')).toBe(
      'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/Stop',
    );
    expect(launcherUrl(PORT, SESSION_ID, 'claude-exit')).toBe(
      'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/launcher/claude-exit',
    );
  });
});

describe('hookCommand', () => {
  it('posts stdin and never fails the session', () => {
    expect(hookCommand(PORT, SESSION_ID, 'PreToolUse')).toBe(
      "curl -s -m 2 -X POST -H 'content-type: application/json' --data-binary @- 'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/PreToolUse' >/dev/null 2>&1 || true",
    );
  });

  it('quotes the url, so the safety does not depend on how a session is named', () => {
    expect(hookCommand(PORT, "qc-DOC-1-'; rm -rf /", 'PreToolUse')).toContain(
      "'http://127.0.0.1:4400/api/hooks/qc-DOC-1-'\\''; rm -rf //PreToolUse'",
    );
  });
});

describe('buildSettings', () => {
  const settings = buildSettings({ sessionId: SESSION_ID, port: PORT, dir: DIR });

  it('subscribes to every hook the state machine consumes', () => {
    expect(Object.keys(settings.hooks)).toEqual([...HOOK_EVENT_NAMES]);
  });

  it('subscribes to both compaction hooks, with no matcher on either', () => {
    // Without them a compaction is a ~20 s silence in which the card reads
    // "your turn" and nothing on the record moves; `PreCompact` is the only
    // report that one started and `PostCompact` the only one that names it.
    for (const event of ['PreCompact', 'PostCompact']) {
      const entry = settings.hooks[event]?.[0];
      expect(entry, event).toBeDefined();
      expect(entry?.matcher).toBeUndefined();
    }
  });

  it('gives every hook a five-second timeout and its own ingress path', () => {
    for (const event of HOOK_EVENT_NAMES) {
      const entry = settings.hooks[event]![0]!;
      expect(entry.hooks).toHaveLength(1);
      expect(entry.hooks[0]!.type).toBe('command');
      expect(entry.hooks[0]!.timeout).toBe(HOOK_TIMEOUT_SECONDS);
      expect(entry.hooks[0]!.command).toContain(`/api/hooks/${SESSION_ID}/${event}`);
    }
  });

  it('matches only the two notification types that mean the owner is needed', () => {
    expect(settings.hooks['Notification']![0]!.matcher).toBe(NOTIFICATION_MATCHER);
    expect(settings.hooks['Stop']![0]!.matcher).toBeUndefined();
  });

  it('overrides the status line with the generated script, refreshed every second', () => {
    expect(settings.statusLine).toEqual({
      type: 'command',
      command: `bash '${DIR}/statusline.sh'`,
      refreshInterval: 1,
    });
  });
});

describe('buildSettingsFile', () => {
  it('renders the exact JSON document', () => {
    const file = buildSettingsFile({ sessionId: SESSION_ID, port: PORT, dir: DIR });

    expect(file).toBe(
      `${JSON.stringify(buildSettings({ sessionId: SESSION_ID, port: PORT, dir: DIR }), null, 2)}\n`,
    );
    expect(file.endsWith('\n')).toBe(true);
  });
});

describe('buildStatuslineScript', () => {
  it('posts the payload in the background and prints nothing without a chain', () => {
    const script = buildStatuslineScript({
      sessionId: SESSION_ID,
      port: PORT,
      chainedCommand: null,
    });

    expect(script).toBe(
      [
        '#!/usr/bin/env bash',
        '# Generated by questionable-choices. Overwritten on every start.',
        '',
        'payload=$(cat)',
        "printf '%s' \"$payload\" | curl -s -m 1 -X POST -H 'content-type: application/json' --data-binary @- 'http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/statusline' >/dev/null 2>&1 &",
        '',
      ].join('\n'),
    );
  });

  it('pipes the same payload into the owner statusline when there is one', () => {
    const script = buildStatuslineScript({
      sessionId: SESSION_ID,
      port: PORT,
      chainedCommand: 'bash ~/.claude/statusline.sh',
    });

    expect(script.endsWith('printf \'%s\' "$payload" | bash ~/.claude/statusline.sh\n')).toBe(true);
  });
});

describe('claudeArgv', () => {
  it('passes the settings file, the issue key, the model and the effort', () => {
    expect(claudeArgv(RUN_CONTEXT)).toEqual([
      '--settings',
      `${DIR}/settings.json`,
      '--name',
      'DOC-1',
      '--model',
      'claude-fable-5-1',
      '--effort',
      'high',
      '--permission-mode',
      'acceptEdits',
    ]);
  });

  it('passes no permission-mode flag for the default sentinel', () => {
    expect(claudeArgv({ ...RUN_CONTEXT, permissionMode: 'default' })).not.toContain(
      '--permission-mode',
    );
  });

  it('bypasses permissions with the flag that really skips the prompts', () => {
    const argv = claudeArgv({ ...RUN_CONTEXT, permissionMode: 'bypassPermissions' });

    expect(argv).toContain(BYPASS_PERMISSIONS_FLAG);
    expect(argv).not.toContain('--permission-mode');
    expect(argv).not.toContain('bypassPermissions');
  });

  it('resumes by claude session id', () => {
    const argv = claudeArgv({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });
    expect(argv.slice(-2)).toEqual(['--resume', 'abc-123']);
  });
});

describe('claudeCommandLine', () => {
  it('reads the prompt out of prompt.txt on a fresh start', () => {
    expect(claudeCommandLine(RUN_CONTEXT)).toBe(
      `'claude' '--settings' '${DIR}/settings.json' '--name' 'DOC-1' '--model' 'claude-fable-5-1' '--effort' 'high' '--permission-mode' 'acceptEdits' "$(cat '${DIR}/prompt.txt')"`,
    );
  });

  it('sends no prompt on a resume', () => {
    const line = claudeCommandLine({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });
    expect(line).toContain("'--resume' 'abc-123'");
    expect(line).not.toContain('prompt.txt');
  });
});

describe('buildRunScript', () => {
  it('renders the whole launcher for a bootstrapped start', () => {
    expect(buildRunScript(RUN_CONTEXT)).toBe(
      [
        '#!/usr/bin/env bash',
        '# Generated by questionable-choices. Overwritten on every start.',
        'set -u',
        '',
        'post() {',
        `  curl -s -m 2 -X POST -H 'content-type: application/json' --data-binary "$2" "http://127.0.0.1:4400/api/hooks/qc-DOC-1-implement/launcher/$1" >/dev/null 2>&1 || true`,
        '}',
        '',
        "post bootstrap-start '{}'",
        '',
        `qc_bootstrap_log='${DIR}/bootstrap.log'`,
        '{ npm ci; } 2>&1 | tee "$qc_bootstrap_log"',
        'status=${PIPESTATUS[0]}',
        'if [ "$status" -ne 0 ]; then',
        `  qc_message=$(tail -n 20 "$qc_bootstrap_log" 2>/dev/null | LC_ALL=C tr '\\011' ' ' | LC_ALL=C tr -d '\\000-\\010\\013\\014\\016-\\037\\177' | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g' | awk '{printf "%s\\\\n", $0}')`,
        '  post bootstrap-failed "{\\"exitCode\\":$status,\\"message\\":\\"$qc_message\\"}"',
        '  exec bash',
        'fi',
        'rm -f "$qc_bootstrap_log"',
        '',
        "post claude-start '{}'",
        '',
        `'claude' '--settings' '${DIR}/settings.json' '--name' 'DOC-1' '--model' 'claude-fable-5-1' '--effort' 'high' '--permission-mode' 'acceptEdits' "$(cat '${DIR}/prompt.txt')"`,
        'status=$?',
        '',
        'post claude-exit "{\\"exitCode\\":$status}"',
        '',
        'exec bash',
        '',
      ].join('\n'),
    );
  });

  it('announces no bootstrap when the checkout is reused', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, needsBootstrap: false });

    expect(script).not.toContain('bootstrap-start');
    expect(script).not.toContain('npm ci');
    expect(script).not.toContain('bootstrap-failed');
  });

  it('announces no bootstrap when the repo configures none', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, bootstrap: null });

    expect(script).not.toContain('bootstrap-start');
    expect(script).not.toContain('bootstrap-failed');
  });

  it('announces no bootstrap on a resume', () => {
    const script = buildRunScript({
      ...RUN_CONTEXT,
      needsBootstrap: false,
      resumeSessionId: 'abc-123',
    });

    expect(script).not.toContain('bootstrap-start');
  });

  it('keeps the window open after claude exits', () => {
    expect(buildRunScript(RUN_CONTEXT).trimEnd().endsWith('exec bash')).toBe(true);
  });

  it('tells the launcher ingress that a resume launch is a resume', () => {
    const script = buildRunScript({ ...RUN_CONTEXT, resumeSessionId: 'abc-123' });

    expect(script).toContain('post claude-start \'{"mode":"resume"}\'');
    expect(script).not.toContain("post claude-start '{}'");
  });

  it('captures the bootstrap output and names the file it keeps it in', () => {
    const script = buildRunScript(RUN_CONTEXT);

    expect(script).toContain(`qc_bootstrap_log='${DIR}/${BOOTSTRAP_LOG_FILE}'`);
    expect(script).toContain(`tail -n ${BOOTSTRAP_TAIL_LINES}`);
    // Through tee rather than a redirect: the owner watching the tmux window
    // must still see the bootstrap run.
    expect(script).toContain('| tee "$qc_bootstrap_log"');
    expect(script).toContain('post bootstrap-failed "{\\"exitCode\\":$status,\\"message\\":');
  });
});

describe('the generated launcher, run by bash', () => {
  let dir = '';

  afterEach(async () => {
    if (dir !== '') await rm(dir, { recursive: true, force: true });
    dir = '';
  });

  /**
   * Runs a generated launcher with stub `curl` and `claude` executables.
   *
   * The stub `claude` is not a convenience: `AGENTS.md` § Tests forbids a test
   * from starting a real one, and the launcher's own command line would resolve
   * whatever is on the developer's PATH.
   *
   * @param bootstrap - Shell command the launcher runs as the bootstrap.
   * @param claudeExit - Exit status the stub `claude` ends with.
   * @returns One entry per POST, in the order the launcher made them.
   */
  async function runLauncher(
    bootstrap: string,
    claudeExit = 0,
  ): Promise<Array<{ url: string; body: string }>> {
    dir = await mkdtemp(join(tmpdir(), 'qc-launcher-'));
    const bin = join(dir, 'bin');
    const log = join(dir, 'posts.tsv');
    await writeFile(join(dir, 'prompt.txt'), 'do the thing\n', 'utf8');
    await writeFile(
      join(dir, 'run.sh'),
      buildRunScript({ ...RUN_CONTEXT, dir, bootstrap, claudeBin: join(bin, 'claude') }),
      'utf8',
    );
    await mkdir(bin, { recursive: true });
    await writeFile(
      join(bin, 'claude'),
      [
        '#!/usr/bin/env bash',
        `printf '%s\\n' "$*" > ${JSON.stringify(join(dir, 'claude-argv.txt'))}`,
        `exit ${String(claudeExit)}`,
        '',
      ].join('\n'),
      'utf8',
    );
    await chmod(join(bin, 'claude'), 0o755);
    await writeFile(
      join(bin, 'curl'),
      [
        '#!/usr/bin/env bash',
        'body=""',
        'url=""',
        'while [ $# -gt 0 ]; do',
        '  case "$1" in',
        '    --data-binary) body="$2"; shift 2;;',
        '    http*) url="$1"; shift;;',
        '    *) shift;;',
        '  esac',
        'done',
        `printf '%s\\t%s\\n' "$url" "$body" >> ${JSON.stringify(log)}`,
        '',
      ].join('\n'),
      'utf8',
    );
    await chmod(join(bin, 'curl'), 0o755);

    // stdin is closed, so the `exec bash` the launcher ends with reads EOF and
    // exits instead of sitting there like the tmux window it is meant for.
    await new Promise<void>((resolve, reject) => {
      const child = spawn('bash', [join(dir, 'run.sh')], {
        env: { ...process.env, PATH: `${bin}:${process.env['PATH'] ?? ''}` },
        cwd: dir,
        stdio: 'ignore',
      });
      child.on('error', reject);
      child.on('close', () => {
        resolve();
      });
    });

    const recorded = await readFile(log, 'utf8');
    return recorded
      .split('\n')
      .filter((line) => line !== '')
      .map((line) => {
        const tab = line.indexOf('\t');
        return { url: line.slice(0, tab), body: line.slice(tab + 1) };
      });
  }

  it('posts a bootstrap failure whose message is the tail of what the bootstrap said', async () => {
    const posts = await runLauncher(
      'printf "first line\\nnpm error code E404\\nnpm error 404 Not Found\\n" >&2; exit 3',
    );

    const failure = posts.find((post) => post.url.endsWith('/bootstrap-failed'));
    expect(failure?.url).toContain('/launcher/bootstrap-failed');
    const body = JSON.parse(failure?.body ?? '') as { exitCode: number; message: string };
    expect(body.exitCode).toBe(3);
    expect(body.message).toContain('npm error 404 Not Found');
    expect(body.message).toContain('first line');
  });

  it('escapes a bootstrap message that would otherwise not be JSON', async () => {
    const posts = await runLauncher(
      'printf \'he said "no" \\\\ and left\\n\\tindented\\n\' >&2; exit 1',
    );

    const failure = posts.find((post) => post.url.endsWith('/bootstrap-failed'));
    const body = JSON.parse(failure?.body ?? '') as { exitCode: number; message: string };
    expect(body.exitCode).toBe(1);
    expect(body.message).toContain('he said "no" \\ and left');
    expect(body.message).toContain(' indented');
  });

  it('launches claude when the bootstrap succeeds, posting no failure', async () => {
    const posts = await runLauncher('printf "installed\\n"', 7);

    expect(posts.map((post) => post.url.split('/').pop())).toEqual([
      'bootstrap-start',
      'claude-start',
      'claude-exit',
    ]);
    // The status, not just the sequence: without it the stub is decorative and
    // nothing notices that the line ran whatever `claude` was on PATH.
    const exit = posts.find((post) => post.url.endsWith('/claude-exit'));
    expect(JSON.parse(exit?.body ?? '')).toEqual({ exitCode: 7 });
    expect(await readFile(join(dir, 'claude-argv.txt'), 'utf8')).toContain('do the thing');
  });

  it('removes the bootstrap log when the bootstrap succeeded', async () => {
    // Nothing prunes <dataDir>/sessions/, so a kept transcript of every
    // successful `npm ci` is there for the life of the data directory.
    await runLauncher('printf "installed\\n"');

    await expect(readFile(join(dir, 'bootstrap.log'), 'utf8')).rejects.toThrow();
  });

  it('keeps the bootstrap log when the bootstrap failed', async () => {
    await runLauncher('printf "boom\\n" >&2; exit 2');

    expect(await readFile(join(dir, 'bootstrap.log'), 'utf8')).toContain('boom');
  });
});
